filter:
    excluded_paths:
        - 'tests/*'
build:
    environment:
        php: '8.0'
    tests:
        override:
            -
                command: composer test
                coverage:
                    file: var/coverage.xml
                    format: php-clover
