on: push

jobs:
  test:
    name: Run tests in PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest
    container: 1maa/php-dev:${{ matrix.php-version }}
    strategy:
      matrix:
        php-version: ["8.1"]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install dependencies
        run: composer install
      - name: Execute test suite
        run: composer test
