on: push

jobs:
  php80-test:
    runs-on: ubuntu-latest
    container: 1maa/php-dev:8.0
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install dependencies
        run: composer install
      - name: Run tests
        run: composer test

  php81-test:
    runs-on: ubuntu-latest
    container: 1maa/php-dev:8.1
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install dependencies
        run: composer install
      - name: Run tests
        run: composer test
